version: "3.8"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./config/development.env
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/client/src
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./config/development.env
    depends_on:
      - mongodb
volumes:
  mongo-data: